apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ex-secret-pod1
  name: ex-secret-pod1
spec:
  containers:
  - image: nginx
    name: ex-secret-pod1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secret-volume
      mountPath: /secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: secret-volume
    secret:
      secretName: user-secret-kubectl
      items: 
      - key: user
        path: user.conf
