apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: my-daemonset
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: my-pod-webserver
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
      - name: my-container-nginx
        image: nginx

  selector:
    matchLabels:
      apps: my-app

