apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: frontend-rs
  labels:
    app: frontend
spec:
  template:
    metadata:
      name: my-pod-webserver
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
      - name: my-container-nginx
        image: nginx

  selector:
    matchLabels:
      apps: my-app
  replicas: 8

