apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: apache-container
    image: httpd
    resources:  
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"

  - name: redis-container
    image: redis
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "256Mi"
