apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  user: YWRtaW4=
  pass: bXktcGFzcy0xMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-vol-env
spec:
  containers:
  - name: redis-container
    image: redis
    envFrom:
    - secretRef:
        name: my-secret
    volumeMounts:
    - name: my-vol
      mountPath: "/etc/my-vol"
      readOnly: true


  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
